name: ðŸš€ 19.1.7 Deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      upload:
        type: boolean
        default: true
      version: # this isn't meant to be changed, its just a variable
        type: string
        default: "19.1.7"

jobs:
  verify-linux-x86_64:
    uses: ./.github/workflows/verify.yml
    with:
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04
      demo_profile: linux_x86_64

  verify-linux-arm:
    uses: ./.github/workflows/verify.yml
    with:
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04-arm
      demo_profile: linux_arm

  # # Mac ARM Removed due to segmentation faults when executing demo
  # verify-macos-14-arm:
  #   uses: ./.github/workflows/verify.yml
  #   with:
  #     version: ${{ inputs.VERSION }}

  #     os: macos-14
  #     demo_profile: mac_arm

  # verify-macos-15-arm:
  #   uses: ./.github/workflows/verify.yml
  #   with:
  #     version: ${{ inputs.VERSION }}

  #     os: macos-15
  #     demo_profile: mac_arm

  # verify-macos-15-intel:
  #   uses: ./.github/workflows/verify.yml
  #   with:
  #     version: ${{ inputs.VERSION }}

  #     os: macos-15-intel
  #     demo_profile: mac_x86_64

  verify-windows-x86_64:
    uses: ./.github/workflows/verify.yml
    with:
      version: ${{ inputs.VERSION }}
      os: windows-latest
      demo_profile: windows_x86_64

  upload-package:
    needs:
      - verify-linux-x86_64
      - verify-linux-arm
      - verify-windows-x86_64
    if: ${{ github.ref == 'refs/heads/main' && inputs.upload == true }}
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: ${{ inputs.VERSION }}
