#!/usr/bin/python
#
# Copyright 2024 - 2025 Khalil Estell and the libhal contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: üöÄ Deploy üêâ LLVM 20

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      upload:
        type: boolean
        default: true
      version: # this isn't meant to be changed, its just a variable
        type: string
        default: 20

jobs:
  verify-linux-x86_64:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Linux x86_64
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04
      host_profile: linux_x86_64
      build_profile: linux_x86_64

  verify-linux-arm:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Linux ARM
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04-arm
      host_profile: linux_arm
      build_profile: linux_arm

  verify-macos-15-intel:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: macOS 15 Intel
      version: ${{ inputs.VERSION }}
      os: macos-15-intel
      host_profile: macos_x86_64
      build_profile: macos_x86_64

  verify-macos-15-arm:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: macOS 15 ARM
      version: ${{ inputs.VERSION }}
      os: macos-15
      host_profile: macos_arm
      build_profile: macos_arm

  verify-windows-x86_64:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Windows x86_64
      version: ${{ inputs.VERSION }}
      os: windows-latest
      host_profile: windows_x86_64
      build_profile: windows_x86_64

  verify-windows-arm:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Windows ARM
      version: ${{ inputs.VERSION }}
      os: windows-11-arm
      host_profile: windows_arm
      build_profile: windows_arm

  verify-linux-x86_64-cortex-m4f:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Linux x86_64 ‚Üí Cortex-M4F
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04
      host_profile: cortex-m4f
      build_profile: linux_x86_64

  verify-linux-arm-cortex-m4:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Linux ARM ‚Üí Cortex-M4
      version: ${{ inputs.VERSION }}
      os: ubuntu-24.04-arm
      host_profile: cortex-m4
      build_profile: linux_arm

  verify-macos-14-arm-cortex-m4f:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: macOS 14 ARM ‚Üí Cortex-M4F
      version: ${{ inputs.VERSION }}
      os: macos-14
      host_profile: cortex-m4f
      build_profile: macos_arm

  verify-macos-15-arm-cortex-m4f:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: macOS 15 ARM ‚Üí Cortex-M4F
      version: ${{ inputs.VERSION }}
      os: macos-15
      host_profile: cortex-m4f
      build_profile: macos_arm

  verify-macos-15-intel-cortex-m4f:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: macOS 15 Intel ‚Üí Cortex-M4F
      version: ${{ inputs.VERSION }}
      os: macos-15-intel
      host_profile: cortex-m4f
      build_profile: macos_x86_64

  verify-windows-x86_64-cortex-m33f:
    uses: ./.github/workflows/verify.yml
    with:
      display_name: Windows x86_64 ‚Üí Cortex-M33F
      version: ${{ inputs.VERSION }}
      os: windows-latest
      host_profile: cortex-m33f
      build_profile: windows_x86_64

  upload-package:
    needs:
      - verify-linux-x86_64
      - verify-linux-arm
      - verify-macos-15-intel
      - verify-macos-15-arm
      - verify-windows-x86_64
      - verify-windows-arm
      - verify-linux-x86_64-cortex-m4f
      - verify-linux-arm-cortex-m4
      - verify-macos-14-arm-cortex-m4f
      - verify-macos-15-arm-cortex-m4f
      - verify-macos-15-intel-cortex-m4f
      - verify-windows-x86_64-cortex-m33f
    if: ${{ startsWith(github.ref, 'refs/tags/') && inputs.upload == true }}
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      version: ${{ inputs.VERSION }}
