name: ğŸš€ deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            demo_profile: mac_x86_64

          - os: macos-15
            demo_profile: mac_arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install CMake & Conan
        run: pipx install conan>=2.18.0

      - name: ğŸ“¡ Add `libhal` conan remote
        run: |
          conan remote add libhal https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: ğŸ“¡ Create and setup default profile
        run: conan profile detect --force

      - name: ğŸ‘ï¸â€ğŸ—¨ï¸ Show conan profile
        run: conan profile show

      - name: ğŸ“¡ Install libhal settings_user.yml
        run: conan config install -sf profiles/baremetal/v2/ https://github.com/libhal/conan-config.git

      - name: ğŸ“¡ Install toolchain profiles
        run: conan config install -tf profiles/ -sf conan/profiles/v1/ .

      - name: ğŸ“¦ Create Conan Package
        working-directory: all
        run: conan create . --version=${{ inputs.version }}

      - name: ğŸ“¦ Build Demos Conan Package
        if: ${{ runner.os != 'Windows' }}
        working-directory: demo
        run: VERBOSE=1 conan build . -pr clang-${{ inputs.version }} -pr ${{ matrix.demo_profile }}

      - name: ğŸ“¦ Build Demos Conan Package
        if: ${{ runner.os == 'Windows' }}
        working-directory: demo
        run: conan build . -pr clang-${{ inputs.version }} -pr ${{ matrix.demo_profile }}

      - name: ğŸ“¡ Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' && runner.os != 'Windows' }}
        env:
          PASSWORD: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN_USER }}
        run: conan remote login -p $PASSWORD libhal $JFROG_USER

      - name: ğŸ“¡ Sign into JFrog Artifactory (Powershell)
        if: ${{ github.ref == 'refs/heads/main' && runner.os == 'Windows' }}
        env:
          PASSWORD: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_ID_TOKEN_USER }}
        run: conan remote login -p $env:PASSWORD libhal $env:JFROG_USER

      - name: ğŸ†™ Upload package to Conan Package Repo
        if: ${{ github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-22.04' }}
        run: |
          conan upload "llvm-toolchain/*" --only-recipe --confirm -r=libhal
