name: ðŸš€ Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ci_20_1_8:
    uses: ./.github/workflows/20.1.8.yml
    with:
      upload: true
    secrets: inherit
  ci_19_1_7:
    uses: ./.github/workflows/19.1.7.yml
    with:
      upload: true
    secrets: inherit
