name: ğŸ” Verify

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      os:
        type: string
        required: true
      demo_profile:
        type: string
        required: true

jobs:
  deploy:
    strategy:
      fail-fast: false

    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install CMake & Conan
        run: pipx install conan>=2.18.0

      - name: ğŸ“¡ Add `libhal` conan remote
        run: |
          conan remote add libhal https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: ğŸ“¡ Create and setup default profile
        run: conan profile detect --force

      - name: ğŸ‘ï¸â€ğŸ—¨ï¸ Show conan profile
        run: conan profile show

      - name: ğŸ“¡ Install libhal settings_user.yml
        run: conan config install -sf profiles/baremetal/v2/ https://github.com/libhal/conan-config.git

      - name: ğŸ“¡ Install toolchain profiles
        run: conan config install -tf profiles/ -sf conan/profiles/v1/ .

      - name: ğŸ“¦ Create Conan Package
        working-directory: all
        run: conan create . --version=${{ inputs.version }}

      - name: ğŸ“¦ Build Demos Conan Package
        if: ${{ runner.os != 'Windows' }}
        working-directory: demo
        run: VERBOSE=1 conan build . -pr clang-${{ inputs.version }} -pr ${{ inputs.demo_profile }} --build=cmake --build=missing:cmake/* -c tools.build:skip_test=True

      - name: ğŸ“¦ Build Demos Conan Package
        if: ${{ runner.os == 'Windows' }}
        working-directory: demo
        run: conan build . -pr clang-${{ inputs.version }} -pr ${{ inputs.demo_profile }} --build=cmake --build=missing:cmake/* -c tools.build:skip_test=True

      - name: â–¶ï¸ Run Demo
        run: demo/build/Release/demo
